name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # -------------------------
  # 1. Checkout & Build Docker
  # -------------------------
  build-image:
    runs-on: [self-hosted, macOS, x64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t adu-ecommerce-app:latest .

  # -------------------------
  # 2. SonarQube Scan
  # -------------------------
  sonar-scan:
    runs-on: [self-hosted, macOS, x64]
    needs: build-image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SonarQube Scan
        run: |
          docker run --rm \
            -v $(pwd):/usr/src \
            -w /usr/src \
            sonarsource/sonar-scanner-cli:latest \
            -Dsonar.projectKey=cicd \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://host.docker.internal:9000 \
            -Dsonar.login=sqp_3365dc2a0df5afcf9bbfaf478a0acb978dd687c9

  # -------------------------
  # 3. Push Docker Image
  # -------------------------
  push-image:
    runs-on: [self-hosted, macOS, x64]
    needs: build-image

    steps:
      - name: Docker Hub Login
        run: |
          echo "Logging in to Docker Hub"
          echo "75382231Ay$" | docker login -u "obidocker380" --password-stdin

      - name: Push Docker Image
        run: |
          docker tag adu-ecommerce-app:latest obidocker380/adu-ecommerce-app:latest
          docker push obidocker380/adu-ecommerce-app:latest

  # -------------------------
  # 4. Deploy to Minikube
  # -------------------------
  deploy-minikube:
    runs-on: [self-hosted, macOS, x64]
    needs: push-image

    steps:
      - name: Deploy to Minikube
        run: |
          # Use Minikube Docker daemon
          eval $(minikube -p minikube docker-env)
          # Apply Kubernetes deployment
          kubectl apply -f kubernates/deployment.yml

      - name: Get Application URL
        run: |
          MINIKUBE_IP=$(minikube ip)
          APP_PORT=80   # Change if your deployment uses a different port
          echo "Application is accessible at: http://$MINIKUBE_IP:$APP_PORT"
